Telegram bot
Ivan-Veselov/jvm-alter-langs-hw pull request #2
Opened 2017-09-24 21:54 UTC by Ivan-Veselov

2017-09-25 08:57 UTC, adkozlov commented
Добавьте, пожалуйста, @dovchinnikov в качестве ревьюера.

2017-10-08 16:15 UTC, dovchinnikov requested changes

2017-10-08 16:15 UTC, dovchinnikov commented on telegram-bot/src/main/scala/ru/spbau/bachelors2015/veselov/bot/MediatorBot.scala
> +      message.text.foreach {
Невозможно читать

2017-10-08 16:15 UTC, dovchinnikov commented on telegram-bot/src/main/scala/ru/spbau/bachelors2015/veselov/bot/MediatorBot.scala
> +                                                          pair._2.isInstanceOf[DefaultState.type] &&
isInstanceOf ? 
DefaultState это объект, почему бы не сравнивать `._2 == DefaultState` ?

2017-12-02 21:26 UTC, closed without merging